#!/bin/sh -u
#+[USAGE]
#+  $0

# Select detele entry by user
SELECTED_ENTRY=$(_m_select_entry)

# Cancel?
[ -z "$SELECTED_ENTRY" ] && exit 0

ENTRY_ID=$(echo "$SELECTED_ENTRY" | _f_list_pick_items entry_id)
ENTRY_FILE=$(_s_entry_file_path "$SELECTED_ENTRY")

# Preview remove entry
if [ ! -f "$ENTRY_FILE" ]; then
  _m_download_entry_file "$SELECTED_ENTRY"
  if [ $? -ne 0 ]; then
    _print_error "This entry download error!"
    exit 3
  fi
fi

if [ -f "$ENTRY_FILE" ]; then
  cat <<- PREVIEW_END 1>&2
+ Preview delete entry ---------------------------

$(head -n 15 < "$ENTRY_FILE")

-------------------------------------------------+
PREVIEW_END
else
  _print_error "File not found!"
  exit 3
fi

# Delete entry?
_prompt_yesno "Do you want to delete this entry?"
if [ $? -eq 0 ]; then
  _m_delete_entry "$ENTRY_ID" "$ENTRY_FILE"
  exit $?
fi

exit 0

