#!/bin/sh -u
#+[USAGE]
#+  $0 {EntryFile}
CMD_NAME=$(basename "$0")
TMP_BODY="${HATEBLOG_TMP_DIR}/${CMD_NAME}.body.$(_now).$$"
TMP_HEADER="${HATEBLOG_TMP_DIR}/${CMD_NAME}.header.$(_now).$$"
TMP_ENTRY="${HATEBLOG_TMP_DIR}/${CMD_NAME}.tx.$(_now).$$"

# Function
cleanup_exit(){
  rm "$TMP_HEADER" "$TMP_BODY" "$TMP_ENTRY" 1>/dev/null 2>&1
  exit $1
}

# Parameters
ENTRY_FILE="$1"
shift

HTTP_RES_OK_CODE=201
URL="entry"

# Check EntryFile format
if [ -f "$ENTRY_FILE" ]; then
  _m_check_xml_format "$ENTRY_FILE"
  if [ $? -eq 0 ]; then
    cat "$ENTRY_FILE" > "$TMP_ENTRY"
  else
    _m_check_md_format "$ENTRY_FILE"
    if [ $? -eq 0 ]; then
      # Convert md to xml
      _s_entry_md2xml "$ENTRY_FILE" > "$TMP_ENTRY"
    else
      # Invalid format
      _print_error "Invalid md file format!"
      exit 1
    fi
  fi
else
  # Not found ENTRY_FILE
  _print_error "File not found: $ENTRY_FILE"
  exit 1
fi

# Request
cat "$TMP_ENTRY" | hblg-req POST "$URL" "$HATEBLOG_CONFIG_FILE" -v "$@" 2>"$TMP_HEADER" 1>"$TMP_BODY"

# Check response
cat "$TMP_HEADER" | grep "^< HTTP/.* ${HTTP_RES_OK_CODE}" 1>/dev/null
if [ $? -eq 0 ]; then
  # Requset success
  cat "$TMP_BODY"
  EXIT_STATUS=0
else
  # Request faild
  cat "$TMP_HEADER" | grep "HTTP" 1>&2
  EXIT_STATUS=1
fi

# Cleanup
cleanup_exit $EXIT_STATUS

