#!/bin/sh
#+[USAGE]
#+  $0 < infile

# Newline mark of hatena blog
NEWLINE="  "

# Add newline mark to continue line
# step 1. Add NL to all line
# step 2. If NL continues more than once, Remove NL
# step 3. Remove NL from blank line & markdown syntax line
sed -e 's/$/'"${NEWLINE}"'/'                      \
-e 's/'"${NEWLINE}${NEWLINE}"'$/'"${NEWLINE}"'/'  \
-e "s/^${NEWLINE}$//"                             \
-e '/^ *[#>|]\{1,\}/s/'"${NEWLINE}"'$//'          \
-e '/^ *- /s/'"${NEWLINE}"'$//'                   \
-e '/^ *[0-9]\{1,\}\. /s/'"${NEWLINE}"'$//'       \
-e '/^ *\[.*\] *$/s/'"${NEWLINE}"'$//'            \
-e '/^```/,/^```/s/'"${NEWLINE}"'$//'             \
| tr '\n' '>'                                     \
| sed 's/'"${NEWLINE}"'>>/>>/g'                   \
| tr '>' '\n'

