#!/bin/sh -u
#+[USAGE]
#+  $0 {NewListLine} [DeleteEntryID]

# Parameters
NEW_LIST_LINE="$1"
DEL_ENTRY_LINE=${2:-''}
LIST_FILE="${HATEBLOG_LIST_FILE}"
LIST_FILE_TMP="${HATEBLOG_TMP_DIR}/list.$(_now).$$.tmp"

# Delete old entry line
if [ -n "$DEL_ENTRY_LINE" ]; then
  sed -i '' "/entry\/${DEL_ENTRY_LINE}>/d" "$LIST_FILE"
fi

# Update list file (append file head)
if [ -n "$NEW_LIST_LINE" ]; then
  mv "$LIST_FILE" "$LIST_FILE_TMP"
  echo "$NEW_LIST_LINE" >> "$LIST_FILE_TMP"

  # Sort by published field
  cat "$LIST_FILE_TMP" | sort -t ">" -k 2,2 -r > "$LIST_FILE"

  rm "$LIST_FILE_TMP" >/dev/null 2>&1
fi

